<?php 
function enqueue_scripts_styles() {
	/* Add Foundation CSS */
    wp_enqueue_style( 'foundation', get_stylesheet_directory_uri().'/assets/css/foundation.min.css' );
    wp_enqueue_style( 'parent-style', get_template_directory_uri().'/style.css' );

    /* Add Foundation JS */
    wp_deregister_script( 'jquery' );
    wp_enqueue_script('jquery', get_stylesheet_directory_uri() . '/assets/js/vendor/jquery.js', '','', true);
    wp_enqueue_script('what-input', get_stylesheet_directory_uri() . '/assets/js/vendor/what-input.js', array('jquery'),'', true);
    wp_enqueue_script('foundation', get_stylesheet_directory_uri() . '/assets/js/vendor/foundation.js', array('jquery'),'', true);
    wp_enqueue_script('custom', get_stylesheet_directory_uri() . '/assets/js/app.js', array('jquery'),'', true);
}
add_action( 'wp_enqueue_scripts', 'enqueue_scripts_styles' );  

function custom_excerpt_length( $length ) {
	return 30;
}
add_filter( 'excerpt_length', 'custom_excerpt_length', 999 );

function add_google_fonts() {

wp_enqueue_style( 'google-fonts', 'https://fonts.googleapis.com/css?family=Raleway:300,400,700', false ); 
}

add_action( 'wp_enqueue_scripts', 'add_google_fonts' );

// ACF Fields

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5957cf3b1ecef',
	'title' => 'Page',
	'fields' => array (
		array (
			'key' => 'field_5957cf439f2f5',
			'label' => 'Page Layout Options',
			'name' => 'page_layout_options',
			'type' => 'flexible_content',
			'instructions' => 'Add an unlimited number of modules with full control over the order.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'595834250c5a5' => array (
					'key' => '595834250c5a5',
					'name' => 'one_column',
					'label' => 'One Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_595834310c5a6',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'image',
							'instructions' => 'Centered image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5958344d0c5a7',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_595834540c5a8',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_595834610c5a9',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_595834870c5aa',
							'label' => 'Link Type',
							'name' => 'link_type',
							'type' => 'radio',
							'instructions' => 'Is this link internal or external?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'internal' => 'internal',
								'external' => 'external',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_595834cf0c5ab',
							'label' => 'Internal Link',
							'name' => 'internal_link',
							'type' => 'page_link',
							'instructions' => 'Link to an internal page of the site.',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_595834870c5aa',
										'operator' => '==',
										'value' => 'internal',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'allow_archives' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_595834e70c5ac',
							'label' => 'External Link',
							'name' => 'external_link',
							'type' => 'url',
							'instructions' => 'Link to an external URL.',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_595834870c5aa',
										'operator' => '==',
										'value' => 'external',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_59585d35add46',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => 'Choose the color of this section\'s background.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5957cf969f2f6' => array (
					'key' => '5957cf969f2f6',
					'name' => 'two_columns_half-half',
					'label' => 'Two Columns Half-Half',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_595858d0aaf20',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_595858d9aaf21',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5957d0159f2f8',
							'label' => 'Column 1',
							'name' => 'column_1',
							'type' => 'wysiwyg',
							'instructions' => 'This column will take up one-half of the space.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5957d0589f2f9',
							'label' => 'Column 2',
							'name' => 'column_2',
							'type' => 'wysiwyg',
							'instructions' => 'This column will take up one-half of the space.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_59586177295a0',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => 'Choose the color of this section\'s background.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5d2be15dd225c' => array(
					'key' => '5d2be15dd225c',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d2be23f4bbf1',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5d2be24decf6d',
							'label' => 'Section Description',
							'name' => 'section_description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5d2be257ecf6e',
							'label' => 'Panel Repeater',
							'name' => 'panel_repeater',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5d2be29decf6f',
									'label' => 'Panel Title',
									'name' => 'panel_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5d2be2a3ecf70',
									'label' => 'Panel Body',
									'name' => 'panel_body',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'5958329025a3c' => array (
					'key' => '5958329025a3c',
					'name' => 'two_columns_small-large',
					'label' => 'Two Columns Small-Large',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_595832a425a3d',
							'label' => 'Column 1',
							'name' => 'column_1',
							'type' => 'wysiwyg',
							'instructions' => 'This column is smaller and only takes up 1/3 of the width.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_595832bc25a3e',
							'label' => 'Column 2',
							'name' => 'column_2',
							'type' => 'wysiwyg',
							'instructions' => 'This column is larger and takes up 2/3 of the width.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5957e30fb53e6' => array (
					'key' => '5957e30fb53e6',
					'name' => 'image_block',
					'label' => 'Image Block',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5957e31db53e7',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => 'Full-width image. Best dimensions: 2000px wide by 1200px high',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'large',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5957e5ad809fc' => array (
					'key' => '5957e5ad809fc',
					'name' => 'repeater',
					'label' => 'Repeater',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5957e5c5809fd',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => 'Large font size for the section title.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5957e5d3809fe',
							'label' => 'Section Subtitle',
							'name' => 'section_subtitle',
							'type' => 'text',
							'instructions' => 'Smaller font size than the section title.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_5958646dc8287',
							'label' => 'Section Description',
							'name' => 'section_description',
							'type' => 'wysiwyg',
							'instructions' => 'Section description',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_5958180024d85',
							'label' => 'Repeated Items',
							'name' => 'repeated_items',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5958181924d86',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_5958181f24d87',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5958182524d88',
									'label' => 'Subtitle',
									'name' => 'subtitle',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5958182924d89',
									'label' => 'Description',
									'name' => 'description',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				)
			),
			'button_label' => 'Add Content Block',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;